import type { CardBackId } from '../../game/state';

export type CardBackPatternVariant = 'damask' | 'lattice' | 'quatrefoil' | 'rays' | 'weave';

export type CardBackPalette = {
  gradient: string;
  border: string;
  accent: string;
  foil: string;
  pattern: CardBackPatternVariant;
  patternOpacity: number;
  text?: string;
  light: boolean;
};

export const cardBackPalettes: Record<CardBackId, CardBackPalette> = {
  emerald: {
    gradient: 'from-[#0f5b43] to-[#092118]',
    border: 'border-[#f5d99b]/40',
    accent: '#f5d99b',
    foil: '#fff4c4',
    pattern: 'damask',
    patternOpacity: 0.15,
    light: false,
  },
  ivory: {
    gradient: 'from-[#f6e7bd] to-[#9b6e3c]',
    border: 'border-[#271811]/45',
    accent: '#3d2a18',
    foil: '#fff8e8',
    pattern: 'quatrefoil',
    patternOpacity: 0.12,
    text: '#142019',
    light: true,
  },
  ruby: {
    gradient: 'from-[#7d1622] to-[#1f0a0d]',
    border: 'border-[#f5d99b]/35',
    accent: '#f5d99b',
    foil: '#ffc9c9',
    pattern: 'lattice',
    patternOpacity: 0.17,
    light: false,
  },
  midnight: {
    gradient: 'from-[#1e2636] to-[#06070b]',
    border: 'border-[#d7b56d]/30',
    accent: '#d7b56d',
    foil: '#f0e2b8',
    pattern: 'rays',
    patternOpacity: 0.16,
    light: false,
  },
  brass: {
    gradient: 'from-[#5a411e] to-[#15100a]',
    border: 'border-[#f5d99b]/40',
    accent: '#f5d99b',
    foil: '#ffe9a8',
    pattern: 'weave',
    patternOpacity: 0.17,
    light: false,
  },
  plaid: {
    gradient: 'from-[#174532] to-[#872d32]',
    border: 'border-[#f5d99b]/25',
    accent: '#f5d99b',
    foil: '#ffd89a',
    pattern: 'lattice',
    patternOpacity: 0.17,
    light: false,
  },
  obsidian: {
    gradient: 'from-[#18181b] to-[#030305]',
    border: 'border-[#f5d99b]/25',
    accent: '#e8d49a',
    foil: '#ffffff',
    pattern: 'damask',
    patternOpacity: 0.15,
    light: false,
  },
  sapphire: {
    gradient: 'from-[#16467c] to-[#061426]',
    border: 'border-[#9dc8ff]/35',
    accent: '#9dc8ff',
    foil: '#e8f4ff',
    pattern: 'rays',
    patternOpacity: 0.17,
    light: false,
  },
  amethyst: {
    gradient: 'from-[#4c1d68] to-[#14051f]',
    border: 'border-[#dfb5ff]/30',
    accent: '#dfb5ff',
    foil: '#f5e6ff',
    pattern: 'quatrefoil',
    patternOpacity: 0.14,
    light: false,
  },
  jade: {
    gradient: 'from-[#0b6b55] to-[#05221b]',
    border: 'border-[#b7f5d8]/28',
    accent: '#b7f5d8',
    foil: '#e8fff5',
    pattern: 'weave',
    patternOpacity: 0.16,
    light: false,
  },
  cherry: {
    gradient: 'from-[#a01634] to-[#23050b]',
    border: 'border-[#ffd1da]/32',
    accent: '#ffd1da',
    foil: '#fff0f3',
    pattern: 'damask',
    patternOpacity: 0.13,
    light: false,
  },
  carbon: {
    gradient: 'from-[#2d333b] to-[#080a0d]',
    border: 'border-[#cbd5e1]/25',
    accent: '#cbd5e1',
    foil: '#f8fafc',
    pattern: 'lattice',
    patternOpacity: 0.14,
    light: false,
  },
  casino: {
    gradient: 'from-[#0f6b3f] via-[#81212d] to-[#18110a]',
    border: 'border-[#f5d99b]/35',
    accent: '#f5d99b',
    foil: '#fff2b8',
    pattern: 'rays',
    patternOpacity: 0.16,
    light: false,
  },
  sunset: {
    gradient: 'from-[#a84b2a] to-[#2a0f12]',
    border: 'border-[#ffd08a]/35',
    accent: '#ffd08a',
    foil: '#fff4d6',
    pattern: 'quatrefoil',
    patternOpacity: 0.14,
    light: false,
  },
  frost: {
    gradient: 'from-[#d8f4ff] to-[#5b7c93]',
    border: 'border-[#10202a]/35',
    accent: '#1a3344',
    foil: '#ffffff',
    pattern: 'weave',
    patternOpacity: 0.12,
    text: '#10202a',
    light: true,
  },
  moss: {
    gradient: 'from-[#4d6428] to-[#121a0c]',
    border: 'border-[#e6d77f]/30',
    accent: '#e6d77f',
    foil: '#f8f2c8',
    pattern: 'damask',
    patternOpacity: 0.14,
    light: false,
  },
  pearl: {
    gradient: 'from-[#fff1d2] to-[#c7b083]',
    border: 'border-[#2c2416]/35',
    accent: '#4a3824',
    foil: '#ffffff',
    pattern: 'lattice',
    patternOpacity: 0.13,
    text: '#142019',
    light: true,
  },
  royal: {
    gradient: 'from-[#243c8f] to-[#090d2b]',
    border: 'border-[#f5d99b]/35',
    accent: '#f5d99b',
    foil: '#dce6ff',
    pattern: 'quatrefoil',
    patternOpacity: 0.14,
    light: false,
  },
  ember: {
    gradient: 'from-[#8e2d16] to-[#160807]',
    border: 'border-[#ffb37b]/35',
    accent: '#ffb37b',
    foil: '#ffe8d4',
    pattern: 'rays',
    patternOpacity: 0.17,
    light: false,
  },
  mint: {
    gradient: 'from-[#9de8c8] to-[#277154]',
    border: 'border-[#09231a]/35',
    accent: '#0a3d2c',
    foil: '#f0fff8',
    pattern: 'weave',
    patternOpacity: 0.12,
    text: '#09231a',
    light: true,
  },
  grape: {
    gradient: 'from-[#67236f] to-[#17071b]',
    border: 'border-[#e7b8ef]/32',
    accent: '#e7b8ef',
    foil: '#fae8ff',
    pattern: 'damask',
    patternOpacity: 0.13,
    light: false,
  },
  slate: {
    gradient: 'from-[#475569] to-[#0f172a]',
    border: 'border-[#cbd5e1]/25',
    accent: '#cbd5e1',
    foil: '#f1f5f9',
    pattern: 'lattice',
    patternOpacity: 0.15,
    light: false,
  },
  rose: {
    gradient: 'from-[#be4767] to-[#2a0b16]',
    border: 'border-[#ffd3dc]/35',
    accent: '#ffd3dc',
    foil: '#fff0f5',
    pattern: 'quatrefoil',
    patternOpacity: 0.13,
    light: false,
  },
  lagoon: {
    gradient: 'from-[#087f8c] to-[#052f37]',
    border: 'border-[#a5f3fc]/30',
    accent: '#a5f3fc',
    foil: '#e8fdff',
    pattern: 'rays',
    patternOpacity: 0.17,
    light: false,
  },
  whiskey: {
    gradient: 'from-[#8a5524] to-[#1a0f07]',
    border: 'border-[#f5d99b]/35',
    accent: '#f5d99b',
    foil: '#ffe4b0',
    pattern: 'weave',
    patternOpacity: 0.17,
    light: false,
  },
  noir: {
    gradient: 'from-[#111827] to-[#020617]',
    border: 'border-[#f8fafc]/22',
    accent: '#e2e8f0',
    foil: '#ffffff',
    pattern: 'damask',
    patternOpacity: 0.13,
    light: false,
  },
  coral: {
    gradient: 'from-[#e26d5c] to-[#33100d]',
    border: 'border-[#ffe0bd]/35',
    accent: '#ffe0bd',
    foil: '#fff8f0',
    pattern: 'lattice',
    patternOpacity: 0.15,
    light: false,
  },
  linen: {
    gradient: 'from-[#eadfc8] to-[#74624a]',
    border: 'border-[#241a10]/35',
    accent: '#3a2c1e',
    foil: '#fffaf0',
    pattern: 'quatrefoil',
    patternOpacity: 0.12,
    text: '#142019',
    light: true,
  },
  orchid: {
    gradient: 'from-[#9d4edd] to-[#230b3a]',
    border: 'border-[#f0c4ff]/35',
    accent: '#f0c4ff',
    foil: '#faf0ff',
    pattern: 'rays',
    patternOpacity: 0.16,
    light: false,
  },
  cobalt: {
    gradient: 'from-[#1d4ed8] to-[#08112f]',
    border: 'border-[#bfdbfe]/35',
    accent: '#bfdbfe',
    foil: '#eff6ff',
    pattern: 'weave',
    patternOpacity: 0.17,
    light: false,
  },
};

export function getCardBackPalette(id: CardBackId): CardBackPalette {
  return cardBackPalettes[id];
}
